export { default as Home } from "./home/Home";
export { default as Category } from "./category/Category";
export { default as ProductInside } from "./product-inside/ProductInside";
export { default as Purchase } from "./purchase/Purchase";
export { default as Favorite } from "./favorite/Favorite";
export { default as Login } from "./login/Login";
export { default as SignUp } from "./sign up/SignUp";
export { default as PersonalCabinet } from "./PersonalCabinet/PersonalCabinet";
export { default as Compare } from "./compare/Compare";
export { default as Search } from "./search/Search";
export { default as Admin } from "./admin/Admin";
export { default as CreateLaptop } from "./admin/create/createLaptop";
export { default as CreatePhone } from "./admin/create/createPhone";
export { default as CreateTablet } from "./admin/create/createTablet";
export { default as UpdateLaptop } from "./admin/update/updateLaptop";
export { default as UpdateTablet } from "./admin/update/updateTablet";
export { default as UpdatePhone } from "./admin/update/updatePhone";
