export { default as Navbar } from "./navbar/Navbar";
export { default as BlackBackground } from "./transparent-black-background/background";
export { default as ProductBoxes } from "./ProductBoxes/ProductBoxes";
export { default as DiscountBoxes } from "./discount boxes/Discount-boxes";
export { default as RecommendBoxes } from "./recommendBoxes/recommendBoxes";
export { default as Footer } from "./Footer/Footer";
export { default as Boxes } from "./boxes/Boxes";
export { default as Category_Accordion } from "./category_accordion/Accordion";
export { default as Filter_inside_product_direction } from "./Filter_inside_product_direction/Filter_inside_product_direction";
export { default as Product_About } from "./Product_about/Product_About";
export { default as AStarter } from "./AStarter/AStarter";
export { default as InterestingProducts } from "./interesting-products/InterestingProducts";
export { default as Main_menu } from "./main_menu/Main_menu";
export { default as LogoutModal } from "./logout confirm modal/logoutModal";
